name: My first workfow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: combine all
              run : |
               echo "welcome to my first actions"
               ls -ltra
               cat README.md